### PR TITLE
Disable JIT optimization for user code.

### PR DESCRIPTION
**Pull request by pgimeno**
That enables normal working of debug.sethook() even for loops. The drawback is that that code will run more slowly.

### CODE REVIEW

**Comment by pgimeno** [comment]
Please check if this works. I think it may be the safest way to go. Otherwise I have prepared a patch along the lines discussed in #254 that inserts function calls in potential loops.

**Comment by Jeija** [comment]
Seems to work for me, I have tested it with a small set of Luacontrollers that are programmed with all kinds of loops / gotos / function calls that could cause DoS. This certainly needs a lot more testing, but if it actually works in the end, the drawback of having code in the luacontroller run minimally slower is by far outweighed by the benefit of
* Having no more prohibited commands in the luacontroller
* Finally no feature disparity between Lua / LuaJIT
* Less code to maintain, which hopefully also means better security

Thank you so much for this patch! It is one of those easy solutions I didn't know existed, so I didn't even think of this!

**Comment by pgimeno** [comment]
Yeah, it's been frustrating for me too to come up with it *after* writing the patch :)

**Comment by Jeija** [comment]
Okay, so you and I (and anyone that came across this PR) haven't found any bugs so far. This code won't test itself, so I will have to merge it and see what happens. Worst case scenario is that some server using mesecons crashes and we have to revert this change... But I don't see that happening.

The only things I have changed from your original commit are some comments. I have also prepared a commit for the mesecons.net luacontroller documentation that I'll upload shortly.

**Pull request closed without merging**
