### PR TITLE
Fix doors texture names

### PR DESCRIPTION
**Pull request by MT-Modder**
Fix doors texture names due to recent changes to minetest_game.
Fixes https://github.com/Jeija/minetest-mod-mesecons/issues/204

Sorry for all the crazyness :) with the pull requests.

### CODE REVIEW

**Comment by Jeija** [comment]
Looks good to me! Thanks.
I just don't like it when mintest_game changes things for no real good reason and without maintaining compatibility. That way, people have to run the latest minetest all the time to have mesecons doors work for them...
Some transition phase might have been useful at least.

**Comment by HybridDog** [comment]
There's a way to support both versions: You could use minetest.registered_nodes.

**Comment by MT-Modder** [comment]
@HybridDog minetest.override_item would be better, but I haven't tried it. I tried your method but couldn't get it to work. Pos was nil for the on_rightclick function.

**Comment by HybridDog** [comment]
You only need to get the "tiles" of the original doors with minetest.registered_nodes to support both versions.

**Comment by MT-Modder** [comment]
Wow I feel silly :) I was looking at it the exact opposite way.

**Pull request merged**
