### PR TITLE
Add more wires to the craftable group

### PR DESCRIPTION
**Pull request by MT-Modder**

### CODE REVIEW

**Comment by MT-Modder** [comment]
Bump

**Comment by Jeija** [comment]
Personally, I'm not in favor of this. It doesn't make sense to me that you could craft the exact same thing using different recipes. That way the same craft ouput could consume different amounts of resources.

**Comment by MT-Modder** [comment]
Then insulated crossover and t-junction should be removed from this group. Should I submit a pull request for it?

**Comment by Jeija** [comment]
@MT-Modder: That would be great, I'd merge such a pull request.

**Comment by MT-Modder** [comment]
Cool I'll get right on it.

**Comment by MT-Modder** [comment]
I decided to just remove the wires from the group so mod creators can use the group if they want to.
Here's the pull: #221

**Pull request closed without merging**
