### PR TITLE
Use dye for lightstone recipes - for balance

### PR DESCRIPTION
**Pull request by MT-Modder**
Currently it is much more expensive to make a yellow lightstone compared to a grey one. This pull request serves to balance these recipes and imo makes more sense.

### CODE REVIEW

**Comment by Jeija** [comment]
Makes sense. Could you create screenshots of the recipes and send a pull request to update the documentation on the webiste? You only have to update the pictures at crafts/lightstone_*.png in the [mesecons.net](https://github.com/Jeija/mesecons.net) repository. That would be really helpful!

**Comment by MT-Modder** [comment]
Sure thing just give me some time :)

**Comment by HybridDog** [comment]
@Jeija May you add this to mesecons.net?
https://github.com/jfix/nyancat

you can test it there:
http://jsfiddle.net/LH3BM/3/embedded/result/

**Comment by MT-Modder** [comment]
Here is the pull: https://github.com/Jeija/mesecons.net/pull/6

**Comment by Jeija** [comment]
Thanks!

**Comment by MT-Modder** [comment]
Np.

**Pull request merged**
