### PR TITLE
Doors: Use new mesh door API if available

### PR DESCRIPTION
**Pull request by sofar**
I've implemented a new door API in minetest_game that
performs all the needed things to assure doors are
properly openend and closed, without mods needing to
know the inner details of what needs to be done.

Mesecons can just fetch a reference to the door object
and call the appropriate open or close method, which
simplifies this code a lot.

For compatibility, this code retains the old code path
and tests whether the new API is available, so this
code remains functional if the new API is not available.

Since the metal trapdoor was only recently added, I added
it to the new API codepath only, it's unlikely to be
present on older versions of minetest_game anyway.

As a benefit from the new door API, there is now
absolutely no more accidental switching closed trapdoors
to open on power off, which could happen with the
old method - since that was just a simple toggle.

### CODE REVIEW

**Comment by sofar** [comment]
@Jeija hey, since this door api is now merged in minetest_game, mesecons crashes the server if you don't merge this patch. I suggest you merge this ASAP.

**Comment by Jeija** [comment]
Thank you, I have just merged your code (with some very slight style changes). However, there is one problem with doors that mesecons has had for a longer time, here is how to reproduce:
* Place some mesecon wires first
* Then place a door (any normal one, not a trapdoor) next to the wire
Issue: The wire won't automatically connect to the door!
This confuses many new users as the door just doesn't appear to work. When placing the door first, however, the wire connects just fine.

I would love to solve this problem, but there is no clean way for me to do it. As doors are craftitems, not nodes, no `minetest.register_on_placenode` event is fired since the doors code places the door nodes with `set_node`, not `place_node`. The only way to solve this I know is to override the whole `on_place` function of doors, which esentially means replicating most of the door code in mesecons.

@sofar Since you wrote the doors code, do you know a good solution to this problem? Maybe doors could use `place_node` instead or provide some kind of hook function?

**Comment by Jeija** [comment]
I will close this PR since I merged it manually and we will track the issue I just mentioned in #220 / minetest_game.

**Comment by sofar** [comment]
https://github.com/minetest/minetest_game/pull/852

**Pull request closed without merging**
