### PR TITLE
fix sticky movestone recipe

### PR DESCRIPTION
**Pull request by DS-Minetest**
You can gain two sticky out of one movestone, this makes not much sense.

### CODE REVIEW

**Comment by Jeija** [comment]
Fair enough, that makes sense. Could you just please also make sure to update the [craft recipe documentation](https://github.com/Jeija/minetest-mod-mesecons/blob/master/mesecons_movestones/doc/movestone_sticky/recipe.png) for mesecons.net?

**Comment by DS-Minetest** [comment]
Done.

**Comment by DS-Minetest** [comment]
So, are there still any problems?

**Comment by Jeija** [comment]
I squashed the commits and manually merged this. Thanks for your contribution and patience 👍

**Pull request closed without merging**
