### PR TITLE
Added more sounds to noteblocks

### PR DESCRIPTION
**Pull request by C1ffisme**
I added another octave to noteblocks, and made some sounds for pranking your friends. They'll run in terror when they hear a fire or tnt sound near their house!

### CODE REVIEW

**Comment by Jeija** [comment]
Could you please document your changes on the http://mesecons.net website by changing this file over here: https://github.com/Jeija/mesecons.net/blob/master/items/noteblock.php ?

**Comment by C1ffisme** [comment]
I'll see what I can do...

**Comment by C1ffisme** [comment]
Should I make a pull request to the github repo?

**Comment by Jeija** [comment]
Yes, that would be great.

**Comment by C1ffisme** [comment]
Right, here I go.

**Comment by C1ffisme** [comment]
[Done.](https://github.com/Jeija/mesecons.net/pull/7)

**Comment by Jeija** [comment]
Hmm, okay, I just realized one thing that I forgot to check before:
In order to make the TNT sound, you would need to have TNT below the noteblock. If, however, mesecons adds support for activating TNT with mesecon signals in the future, that would set off all the noteblocks of people using this feature...
Maybe you could use some other node for this? Like a coal block or something like that?

**Comment by C1ffisme** [comment]
This isn't always true. If you build something where the mesecon is __Above__ the noteblock, then it is safe. But since this may cause frustration in the future, I will set it to gunpowder, since gunpowder is not activated by mesecons.

**Comment by VanessaE** [comment]
I would go with Jeija's suggestion here, as gunpowder is just a flat item while coal block is..well..a block.  Besides, some games might choose in the future, to trigger gunpowder with a mesecons signal also.

**Comment by C1ffisme** [comment]
Right, okay, changing.

**Comment by C1ffisme** [comment]
Is this pull request still active? It's had the explosion sound changed to a coal block now. Do you want to merge?

**Comment by Jeija** [comment]
I just merged it manually.

**Pull request closed without merging**
